//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""DebugActionMap"",
            ""id"": ""4dc26683-fee8-494c-8057-63126d590022"",
            ""actions"": [
                {
                    ""name"": ""ToggleDebugView"",
                    ""type"": ""Button"",
                    ""id"": ""4a27e432-9eb6-4ae7-857b-1183b4cfde5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""43a238ae-45c9-4954-a255-7bb12bff3f9d"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDebugView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DebugActionMap
        m_DebugActionMap = asset.FindActionMap("DebugActionMap", throwIfNotFound: true);
        m_DebugActionMap_ToggleDebugView = m_DebugActionMap.FindAction("ToggleDebugView", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DebugActionMap
    private readonly InputActionMap m_DebugActionMap;
    private List<IDebugActionMapActions> m_DebugActionMapActionsCallbackInterfaces = new List<IDebugActionMapActions>();
    private readonly InputAction m_DebugActionMap_ToggleDebugView;
    public struct DebugActionMapActions
    {
        private @Controls m_Wrapper;
        public DebugActionMapActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleDebugView => m_Wrapper.m_DebugActionMap_ToggleDebugView;
        public InputActionMap Get() { return m_Wrapper.m_DebugActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IDebugActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugActionMapActionsCallbackInterfaces.Add(instance);
            @ToggleDebugView.started += instance.OnToggleDebugView;
            @ToggleDebugView.performed += instance.OnToggleDebugView;
            @ToggleDebugView.canceled += instance.OnToggleDebugView;
        }

        private void UnregisterCallbacks(IDebugActionMapActions instance)
        {
            @ToggleDebugView.started -= instance.OnToggleDebugView;
            @ToggleDebugView.performed -= instance.OnToggleDebugView;
            @ToggleDebugView.canceled -= instance.OnToggleDebugView;
        }

        public void RemoveCallbacks(IDebugActionMapActions instance)
        {
            if (m_Wrapper.m_DebugActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugActionMapActions @DebugActionMap => new DebugActionMapActions(this);
    public interface IDebugActionMapActions
    {
        void OnToggleDebugView(InputAction.CallbackContext context);
    }
}
